version: '3.7'

#list of services to be deployed which include nginx, go app and java app

services:
#deploy go-app from the binary and use dockerfile
  go-app:
    build: ./golang-webserver
    hostname: go-app
    port:
      - "5001:8080"
    networks: 
      - backend
      - frontend

#deploy the java app
  java-app:
    build: ./java-webserver
    hostname: java-app
    port:
      - "5002:8080"
    networks: 
      - backend
      - frontend

#nginx load balancer
  nginx:
    image: nginx:1.15
    depends_on: 
      - go-app
      - java-app
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 8081:80
    networks: 
      - frontend
      - backend
	
#deploy networks
networks:
  backend:
  frontend:
